//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CouchDBDeployCmdlets.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CouchDBDeployCmdlets.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CouchDB Worker Role {0} has been created with {1} instances at &apos;{2}&apos;. By default only local storage is set in the configuration. Please make sure to call Set-AzureCouchStorageAccount command to set Windows Azure Storage account before publishing your service to Windows Azure..
        /// </summary>
        internal static string AddAzureCouchWorkerRoleSuccessMessage {
            get {
                return ResourceManager.GetString("AddAzureCouchWorkerRoleSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InstallLocation.
        /// </summary>
        internal static string AzureCouchDBRegistryInstallLocationKey {
            get {
                return ResourceManager.GetString("AzureCouchDBRegistryInstallLocationKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software\CouchDB\CouchDBInstWR.
        /// </summary>
        internal static string AzureCouchDBRegistrySectionName {
            get {
                return ResourceManager.GetString("AzureCouchDBRegistrySectionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Azure SDK/v1.6/bin.
        /// </summary>
        internal static string AzureSdkBinFolder {
            get {
                return ResourceManager.GetString("AzureSdkBinFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Azure SDK Deployment Cmdlets.
        /// </summary>
        internal static string AzureSdkDirectoryName {
            get {
                return ResourceManager.GetString("AzureSdkDirectoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t find {0} directory. Please run Import-AzureService -Path cmdlet to create {0} directory..
        /// </summary>
        internal static string AzureSdkDirectoryNotFound {
            get {
                return ResourceManager.GetString("AzureSdkDirectoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage account &apos;{0}&apos; already exists..
        /// </summary>
        internal static string AzureStorageAccountAlreadyExistsMessage {
            get {
                return ResourceManager.GetString("AzureStorageAccountAlreadyExistsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage account &apos;{0}&apos; configured for the CouchDB role &apos;{1}&apos;..
        /// </summary>
        internal static string AzureStorageAccountConfiguredForCouchRoleMessage {
            get {
                return ResourceManager.GetString("AzureStorageAccountConfiguredForCouchRoleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage account &apos;{0}&apos; created..
        /// </summary>
        internal static string AzureStorageAccountCreatedMessage {
            get {
                return ResourceManager.GetString("AzureStorageAccountCreatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate.cer.
        /// </summary>
        internal static string CertificateFileName {
            get {
                return ResourceManager.GetString("CertificateFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No certificate was found in the certificate store with thumbprint {0}..
        /// </summary>
        internal static string CertificateNotFoundInStore {
            get {
                return ResourceManager.GetString("CertificateNotFoundInStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to download CouchDB binaries..
        /// </summary>
        internal static string CouchDBBinariesDownloadFailedMessage {
            get {
                return ResourceManager.GetString("CouchDBBinariesDownloadFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WorkerRole\CouchDB.
        /// </summary>
        internal static string CouchDBBinariesDownloadScriptArguments {
            get {
                return ResourceManager.GetString("CouchDBBinariesDownloadScriptArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CouchDbScaffolding\WorkerRole\downloadcouchdb.ps1.
        /// </summary>
        internal static string CouchDBBinariesDownloadScriptName {
            get {
                return ResourceManager.GetString("CouchDBBinariesDownloadScriptName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CouchDB 1.1.1 installation failed. You may try installing CouchDB 1.1.1 yourself from the Apache site and retry..
        /// </summary>
        internal static string CouchDBBinariesDownloadScriptNotAvailable {
            get {
                return ResourceManager.GetString("CouchDBBinariesDownloadScriptNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully downloaded CouchDB binaries from Apache site..
        /// </summary>
        internal static string CouchDBBinariesDownloadSuccessMessage {
            get {
                return ResourceManager.GetString("CouchDBBinariesDownloadSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CouchDB binaries not available. You may try installing CouchDB 1.1.1 yourself from the Apache site and retry..
        /// </summary>
        internal static string CouchDBBinariesNotAvailableMessage {
            get {
                return ResourceManager.GetString("CouchDBBinariesNotAvailableMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WorkerRole\CouchDB\Install.exe.
        /// </summary>
        internal static string CouchDBBinaryFileName {
            get {
                return ResourceManager.GetString("CouchDBBinaryFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CouchDBDataDir.
        /// </summary>
        internal static string CouchDBDataDir {
            get {
                return ResourceManager.GetString("CouchDBDataDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to workerrole.
        /// </summary>
        internal static string CouchScaffoldFolder {
            get {
                return ResourceManager.GetString("CouchScaffoldFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating storage service {0}.
        /// </summary>
        internal static string CreateStorageAccountWaitMessage {
            get {
                return ResourceManager.GetString("CreateStorageAccountWaitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataConnectionString.
        /// </summary>
        internal static string DataConnectionStringSettingName {
            get {
                return ResourceManager.GetString("DataConnectionStringSettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft.WindowsAzure.Plugins.Diagnostics.ConnectionString.
        /// </summary>
        internal static string DiagnosticsConnectionString {
            get {
                return ResourceManager.GetString("DiagnosticsConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WorkerRole\InstallNodeJSModules.ps1.
        /// </summary>
        internal static string InstallNodeJsModuleScriptName {
            get {
                return ResourceManager.GetString("InstallNodeJsModuleScriptName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script file required to install node js module is not available..
        /// </summary>
        internal static string InstallNodeJSModuleScriptNotAvailable {
            get {
                return ResourceManager.GetString("InstallNodeJSModuleScriptNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid certificate format. Publish settings may be corrupted. Use Get-AzurePublishSettings to download updated settings..
        /// </summary>
        internal static string InvalidCertificate {
            get {
                return ResourceManager.GetString("InvalidCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file extension. This command works only on *{0} file extension.
        /// </summary>
        internal static string InvalidFileFormatMsg {
            get {
                return ResourceManager.GetString("InvalidFileFormatMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} doesn&apos;t exist in {1} or you&apos;ve not passed valid value for it..
        /// </summary>
        internal static string InvalidPath {
            get {
                return ResourceManager.GetString("InvalidPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided publish settings file {0} has invalid content. Please get valid by running cmdlet Get-AzurePublishSettings..
        /// </summary>
        internal static string InvalidPublishSettingsSchema {
            get {
                return ResourceManager.GetString("InvalidPublishSettingsSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid number of instances specified. Role must have at least one instance..
        /// </summary>
        internal static string InvalidRoleInstancesMessage {
            get {
                return ResourceManager.GetString("InvalidRoleInstancesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AzureDriveCache.
        /// </summary>
        internal static string LocalStorageAzureDriveCache {
            get {
                return ResourceManager.GetString("LocalStorageAzureDriveCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CouchDBLocalDataDir.
        /// </summary>
        internal static string LocalStorageCouchDBLocalDataDir {
            get {
                return ResourceManager.GetString("LocalStorageCouchDBLocalDataDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CouchInstall.
        /// </summary>
        internal static string LocalStorageCouchInstall {
            get {
                return ResourceManager.GetString("LocalStorageCouchInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .PublishSettings.
        /// </summary>
        internal static string PublishSettingsFileExtention {
            get {
                return ResourceManager.GetString("PublishSettingsFileExtention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure.PublishSettings.
        /// </summary>
        internal static string PublishSettingsFileName {
            get {
                return ResourceManager.GetString("PublishSettingsFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish settings imported.
        /// </summary>
        internal static string PublishSettingsSetSuccessfully {
            get {
                return ResourceManager.GetString("PublishSettingsSetSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scaffolding.
        /// </summary>
        internal static string ScaffoldingFolder {
            get {
                return ResourceManager.GetString("ScaffoldingFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServiceConfiguration.Cloud.cscfg.
        /// </summary>
        internal static string ServiceConfigurationCloudFileName {
            get {
                return ResourceManager.GetString("ServiceConfigurationCloudFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServiceConfiguration.Local.cscfg.
        /// </summary>
        internal static string ServiceConfigurationLocalFileName {
            get {
                return ResourceManager.GetString("ServiceConfigurationLocalFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServiceDefinition.csdef.
        /// </summary>
        internal static string ServiceDefinitionFileName {
            get {
                return ResourceManager.GetString("ServiceDefinitionFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}Deploy.
        /// </summary>
        internal static string ServiceDeploymentName {
            get {
                return ResourceManager.GetString("ServiceDeploymentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide name for the hosted service..
        /// </summary>
        internal static string ServiceNameMissingMessage {
            get {
                return ResourceManager.GetString("ServiceNameMissingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://{0}.cloudapp.net.
        /// </summary>
        internal static string ServiceUrl {
            get {
                return ResourceManager.GetString("ServiceUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to deploymentSettings.json.
        /// </summary>
        internal static string SettingsFileName {
            get {
                return ResourceManager.GetString("SettingsFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/setup.cmd.
        /// </summary>
        internal static string SetupCmdPath {
            get {
                return ResourceManager.GetString("SetupCmdPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided subscription name doesn&apos;t exist in the imported publish profile. If subscriptions have changed for the hosted service, retrieve an updated profile by using Get-AzurePublishSettings then import the profile using Import-AzurePublishSettings..
        /// </summary>
        internal static string SubscriptionIdNotFoundMessage {
            get {
                return ResourceManager.GetString("SubscriptionIdNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CouchDB Worker Role {0} already exists. Instance count updated to {1}..
        /// </summary>
        internal static string UpdateAzureCouchWorkerRoleSuccessMessage {
            get {
                return ResourceManager.GetString("UpdateAzureCouchWorkerRoleSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait....
        /// </summary>
        internal static string WaitMessage {
            get {
                return ResourceManager.GetString("WaitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CouchHostWorkerRole.
        /// </summary>
        internal static string WorkerRole {
            get {
                return ResourceManager.GetString("WorkerRole", resourceCulture);
            }
        }
    }
}
